### ISSUE TITLE
What is Kilo in comparison to Service Mesh softwares like Istio?

### ISSUE THREAD

**Issue by nicop311** [squat/kilo#10]
Hi,
I was wondering, what is **Kilo** in comparison to Service Mesh softwares such as **Linkerd**, **Linkerd2** (formerly Conduit), **Consul** and **Istio**?

Service Mesh softwares list source: https://kubedex.com/istio-vs-linkerd-vs-linkerd2-vs-consul/

## How do I know about Kilo?

I heard about **Kilo** by reading the schedule of the 2019 _Open Networking Summit Europe_ conference: 
_Connecting Kubernetes Clusters Across Clouds With Kilo_
Source: https://events.linuxfoundation.org/events/open-networking-summit-europe-2019/

## What is Kilo?

I think I understand the difference between **Kilo** and the Container Network Interface (CNI like Calico and Flannel): the scope of a CNI is one node. CNI is a network plugin for the containers/pods running in one node.

But I don't understand the difference between **Kilo** and Service Mesh softwares like **Istio**.

My initial understanding is that **Kilo** is different than Istio & co. **Kilo** connects together K8s nodes _that can span across data centers and public clouds_ via WireGuard VPN.
Therefore, thanks to **Kilo**, it is like if the apps and services running on these distributed K8s nodes within these different Cloud operators where running on the same "virtual (overlay) cloud".

So maybe **Kilo** is working at a lower level than Service Mesh solutions like **Istio**?

**But I am not sure about this.**

Thank you for any input you can share on this question!
Sorry if this post/question does not suit the github issues topics.

--
Nicop311

**Comment by squat** [comment]
@nicop311 thanks for taking a look at Kilo! Yes, you are right when you say:

> So maybe Kilo is working at a lower level than Service Mesh solutions like Istio

Kilo sets up a fully routable L3 network between nodes in the cluster so that every Pod in the cluster can communicate with every other Pod regardless of which cloud provider they are running in. This means managing the Kubernetes Pod network. Setting up a routable Pod network is the same thing that projects like Flannel, Calico, and Cilium do. The difference between those projects is that Kilo can operate across clouds and data centers.

Service mesh projects operate at higher levels of the network stack e.g. transport (TCP) and application (HTTP, gRPC). These projects provide a different set of benefits including: request routing, load-balancing, discovery, etc.

These two technologies compliment each other. For example, just as we use service-meshes on top of Flannel, using a service mesh to optimize request routing in a geographically- and cloud-distributed cluster created with Kilo could help optimize service performance.

**Comment by nicop311** [comment]
@squat Many thank you for this explanation!

I have some other questions: maybe the answers are in the doc. Feel free to answer or not!

## Route sharing and VPN?

> Kilo sets up a fully routable L3 network between nodes in the cluster so that every Pod in the cluster can communicate with every other Pod regardless of which cloud provider they are running in.

To achieve this _fully routable L3_, are you relying on some kind of _Route Based VPN_ feature that is maybe part of WireGuard VPN in order to share the routes across the multiple cloud providers?

I'm asking this because configuring the routes can be tricky when the number of VPN gateways rises.

**Source "Route Based VPN with wireguard":** https://vincent.bernat.ch/en/blog/2018-route-based-vpn-wireguard

## Make the most out of Kilo and Service Mesh?

> Service mesh projects operate at higher levels of the network stack
> These two technologies compliment each other.

Okay great. So for example, for the L3 "point-to-point/mesh VPN" (~tunnels like what you would do with IPsec, but using wireguard instead) between the he multiple cloud providers, you could imagine run **Kilo** on the multiple cloud providers' instances of K8s.

And on top of **Kilo**, which provides the L3 connectivity, you set up **Istio**, which provides TLS/HTTP, and the other useful features. All of this between multiple cloud providers, and each of them are running **Kilo** + **Istio**.

## How to handle the installation of **Kilo**?

> The difference between [Kilo and Flannel/Calico] is that Kilo can operate across clouds and data centers.

I missed this section of the Doc "the Add-on mode": https://github.com/squat/kilo#add-on-mode  .

So you can deploy your Kubernetes Cluster with the flavor you like (OpenShift too?). As long as you are using Flannel as the CNI component, you can then add **Kilo** and use the features it brings.

I think **Kilo** addresses a very interesting topic with all the hybrid clouds trend, edge computing architectures, etc..

--
Nicop311

**Comment by squat** [comment]
> To achieve this fully routable L3, are you relying on some kind of Route Based VPN feature that is maybe part of WireGuard VPN in order to share the routes across the multiple cloud providers?

Creating the fully routable network is cloud-provider agnostic and does not use VPN gateways and the like. This is managed entirely by Kilo by creating standard Linux route table entries and by leveraging the crypto-key routing of WireGuard. There is no need for users to manage the route table at all.

> As long as you are using Flannel as the CNI component, you can then add Kilo and use the features it brings.

Let me clarify: you can use Kilo with or without Flannel on any cluster. Kilo is a fully capable or managing all CNI for a cluster. If you have a cluster that already has Flannel installed and don’t want to take anything apart, then you can install Kilo on top of Flannel in compatibility mode. You can now bring in nodes from other location or simply make use of multi-cluster or other advanced Kilo feautures.

> OpenShift too?

Soon! OpenShift 4 support is in progress. This is a little trickier because OpenShift has a mandatory cluster networking solution, so Kilo needs to be able to run in compatibility mode on top of that.

**Comment by nicop311** [comment]
Thank you for these inputs. I will maybe try Kilo later this year.

I might have a few questions about WireGuard, and on how Kilo handles (or not?) the crypto-keys for WireGuard.
But I should first read more about WireGuard before. And your documentation.

So I think we can close this issue for the moment.
--
Nicop311

**Comment by squat** [comment]
Sounds good. Please don't hesitate to ask more questions (: closing for now
