### ISSUE TITLE
Kilo on EKS Documentation

### ISSUE THREAD

**Issue by xadcoh** [squat/kilo#110]
Hello

Is there any documentation on how to run the kilo on EKS?

I can see manifests for k3s, typhoon, kubeadm and clusters with flannel but what about k8s-as-a-service such as AKS, GKE, EKS.

Thanks

**Comment by squat** [comment]
Hi @xadcoh, running Kilo on any hosted K8s solution depends entirely on the networking provider in use and the potential to swap this provider for Kilo if necessary. Unfortunately, these hosted platforms cannot typically offer this level of flexibility because it makes their offering too difficult to support. For this reason, Kilo will mostly depend on implementing compatibility layers with other networking providers in order to run on hosted platforms.

Currently, Kilo can run on top of Flannel, so that means it can support hosted Kubernetes platforms that use this provider. I know that some platforms use Cilium, which Kilo does not yet support. However, there are outstanding issues/community members targeting the implementation of a compatibility layer.
The project would be very happy to accept any PRs providing advice :)

**Comment by xadcoh** [comment]
Thank you very much for clarifying this, @squat ! Maybe it could be helpful to add your comment to the main Readme.
