### ISSUE TITLE
Question: Adding another server node.

### ISSUE THREAD

**Issue by ssoriche** [squat/kilo#176]
I've successfully set up a single node k3s server node with kilo, and now I want to add another node to the cluster (a server node for HA). I've been searching for a process to follow to do this, that doesn't involve rebuilding my cluster (though I couldn't find anything that suggested that as a solution either). Is there a process for adding nodes to an existing cluster with kilo installed?

Sorry for opening an issue to ask a question.

**Comment by leonnicolas** [comment]
> I've successfully set up a single node k3s server node with kilo, and now I want to add another node to the cluster (a server node for HA). I've been searching for a process to follow to do this, that doesn't involve rebuilding my cluster (though I couldn't find anything that suggested that as a solution either). Is there a process for adding nodes to an existing cluster with kilo installed?

I am not sure if Kilo can run on a HA k3s cluster because it uses a kubeconfig that you have to copy to all nodes. It will use the IP or DNS name in that config to talk to the API server. So if the endpoint dies the Kilo pods won't be able to reach the API server anymore. Maybe you can achieve HA if the DNS name resolves to all API server's IP addresses?

Other than that Kilo doesn't really care if it is running in an HA cluster or not and you should follow the vendor's docs. For example the rancher docs for k3s: https://rancher.com/docs/k3s/latest/en/installation/ha-embedded/

> Sorry for opening an issue to ask a question.

We have a brand new slack channel!! https://slack.k8s.io/ the channel name is #kilo

**Comment by squat** [comment]
Hi @ssoriche Kilo should work out of the box the same way that your kubectl is able to talk to a HA API. If kubectl is able to talk to a HA K3s API then Kilo should too. To get this to work though, you'll need to copy over the new kubeconfig (if the API endpoints changed) to all of the nodes into the correct place so that the Kilo pods can read it. If the HA API is using a DNS name, then this should just work ™

**Comment by squat** [comment]
We just chatted a bit more on the #kilo slack channel in the Kubernetes slack and @ssoriche confirmed that Kilo is working as expected. The source of the trouble was the the K3s cluster needed to be initiated with the `--cluster-init` flag to enable high availability. <3
