### ISSUE TITLE
[QUESTION] Bootstrapping NATed nodes?

### ISSUE THREAD

**Issue by brianthelion** [squat/kilo#182]
Hi, and thanks for the great effort here!

I have a NATed node use-case that `kilo` might be perfect for, and am trying to evaluate a few things. In what follows, I will recap my understanding and then ask a few questions. If any of this is wrong, please correct me:

## Background on k8s and VPNs

When a new Kubernetes node is [bootstrapped](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-join/#join-workflow) from behind a NAT firewall, the basic assumptions of the Kubernetes network model are violated. As a result:

A) The API server cannot push anything (pods, CNI config, etc) to the node.
B) The new node *can* however make requests of the API server.

One way to make sure that the network model is *not* violated by NAT is to put all the nodes in a VPN together, and run Kubernetes over the VPN network interface on each node. This is what many people with NATed nodes are currently doing. The downside of this approach is that:

C) VPN setup and key exchange has to be done "out of band," resulting in yet another node bootstrapping step.
D) Kubernetes isn't itself "aware" of the VPN and does not manage any services, roles, keys, QoS, etc., related thereto.

## `kilo` to the rescue

For NAT use-cases, `kilo` solves (C) and (D) by somehow using (B) for key exchange.

## Questions

1. What are the actual steps for boostrapping a NATed node with `kilo`?
2. Do administrators of NATed nodes require `kubectl` access in order to run `kgctl`?
3. The fact that (B) works is kindof a hack. Does `kilo` have a workaround in mind if this hack goes away?

## Thanks!

Looking forward to any feedback, @squat .

**Comment by leonnicolas** [comment]
Hi @brianthelion 

> I have a NATed node use-case that `kilo` might be perfect for, and am trying to evaluate a few things. In what follows, I will recap my understanding and then ask a few questions. If any of this is wrong, please correct me:

What do you mean with NATed node use-case? Do you have nodes behind one ore more NATs, are any of the nodes not behind NAT and where is your API Server running?
 
> When a new Kubernetes node is [bootstrapped](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-join/#join-workflow) from behind a NAT firewall, the basic assumptions of the Kubernetes network model are violated. As a result:
> 
> A) The API server cannot push anything (pods, CNI config, etc) to the node.

Honestly, I am not aware that the API server pushes anything to nodes. I think the kubelet on each node makes requests to the API server. The kubelet's requests to the API server are over TLS and have nothing to do with Kilo. However, you have no working pod network or services.

> B) The new node _can_ however make requests of the API server.

Yes

> For NAT use-cases, `kilo` solves (C) and (D) by somehow using (B) for key exchange.

Yes, the key exchange happens over annotation to the nodes. Each node will annotate itself with its public key . Other nodes can see the annotations by making requests to the API Server. 

>     1. What are the actual steps for boostrapping a NATed node with `kilo`?

 1. Join the node with the API server eg `kubeadm join`
 2. Make sure the kubelet can talk to the API server. You should be able to see it with `kubectl get nodes`
 3. Put the node(s) behind NAT in a different location `kubectl annotate node <node behind nat> kilo.squat.ai/location=<some other location>`
 4. Apply Kilo

If your API server is behind NAT, you will have to port forward on the router or firewall. Otherwise the kubelet won't be able to reach the API server and annotate the API server node with `kilo.squat.ai/force-endpoint=<dns or ip:port>`. If you are using k3s, you can't join nodes from outside the NAT to an API server behind NAT. That's annoying :(.

>     2. Do administrators of NATed nodes require `kubectl` access in order to run `kgctl`?

Only the API server must be reachable for `kubectl` and `kgctl`. They both require a kubeconfig with an endpoint.

>     3. The fact that (B) works is kindof a hack. Does `kilo` have a workaround in mind if this hack goes away?

No, there must be some kind of initial connectivity to the API server.

The new cool thing is, that Kilo enables full pod connectivity, even when nodes are behind different NATs. This requires one node with a public endpoint though. There will be some documentation about this soon.

**Comment by brianthelion** [comment]
@squat Thanks for your reply. Super helpful!

> What do you mean with NATed node use-case? Do you have nodes behind one ore more NATs, are any of the nodes not behind NAT and where is your API Server running?

Yes, my API server node has a public IP. All the other nodes are in private networks, behind firewalls, with no options for port-forwarding.

> > For NAT use-cases, `kilo` solves (C) and (D) by somehow using (B) for key exchange.
> 
> Yes, the key exchange happens over annotation to the nodes. Each node will annotate itself with its public key . Other nodes can see the annotations by making requests to the API Server.

Very clever!

> >
> > 1. What are the actual steps for boostrapping a NATed node with `kilo`?
> >
> 
> 1. Join the node with the API server eg `kubeadm join`
> 2. Make sure the kubelet can talk to the API server. You should be able to see it with `kubectl get nodes` 
> 3. Put the node(s) behind NAT in a different location `kubectl annotate node <node behind nat> kilo.squat.ai/location=<some other location>`
> 4. Apply Kilo

I will give this a try over the next few days and report back.

Thanks again!

**Comment by brianthelion** [comment]
@squat @leonnicolas 

I have `kilo` working *without* any NATed nodes using QEMU/KVM VMs on my local machine. The next step in my experiment will be to move one or more of these nodes into a separate virtual address space and restrict traffic ingress to that space, eg, to simulate NAT.

What will I need to change in my `kilo` setup to reflect the added NAT complication?

**Comment by squat** [comment]
Hi @brianthelion you will have to set the `kilo.squat.ai/location` [0] annotation on the nodes that are moving to a new address space so that Kilo understands the topology of the cluster. This annotation is used to group nodes into logical locations where the nodes within a location can all communicate on a LAN without the need for WireGuard but need a WireGuard link to communicate with nodes in other locations.

[0] https://kilo.squat.ai/docs/annotations#location

**Comment by brianthelion** [comment]
@squat That appears to have worked. Is there an easy way to test pod-to-pod communication across `kilo`?

**Comment by leonnicolas** [comment]
I have been using/writing this https://github.com/heptoprint/adjacency

**Comment by squat** [comment]
closing this for now since everything seems to be working. @brianthelion please re-open if you have any more issues :))
