### ISSUE TITLE
annotation force-external-ip with alternative dns domain usage

### ISSUE THREAD

**Issue by huapox** [squat/kilo#24]
Current anno: `kilo.squat.ai/force-external-ip="a.b.c.d/32"`

But sometimes we just use a dymanic ip from network provider, thus we use a ddns domain to get the correct wan-ip.

**Comment by squat** [comment]
This is totally cool feature of WireGuard that would be awesome to bring to kilo. I’ve just been a bit lazy to implement it :p one note about dens, I think that WireGuard only resolves the dns name one time, so as soon and the IP for your machine changes, the WireGuard endpoint would be stale.

There’s two ways to make this work: 
1. Let kilo resolve the domain itself early in the chain and put an IP in the configuration for the endpoint; this is the least invasive
2. Pass the domain to WireGuard as part of the actual WireGuard conf. This is more “correct” but would also be would be more work. I don’t this this will work however because WireGuard resolves the dns name and then next time you ask WireGuard for its version of the conf (for reconciliation), WireGuard gives you configuration with the IP rather than the dns name. This means that Kilo’s reconciliation would always detect a changed WireGuard configuration and would constantly try to reset it. There could be ways to remediate this by allowing the reconciler to also resolve dns names for the sake of comparison. This would actually give Kilo the power to update the endpoint in the case of ddns updates.

What do you think?

**Comment by huapox** [comment]
@squat Good anaylsis!  I preffer the first one, stay the dns logic in the upper layer, keep the wireguard standard, for a clear arch and less work to do.

**Comment by squat** [comment]
hi @huapox after a long delay, this feature is finally done! Please take a look at the updated docs to see how to use it :) https://github.com/squat/kilo/blob/master/docs/annotations.md#force-endpoint

**Comment by huapox** [comment]
> hi @huapox after a long delay, this feature is finally done! Please take a look at the updated docs to see how to use it :) https://github.com/squat/kilo/blob/master/docs/annotations.md#force-endpoint

Great! I'll have a try with this feature, and give some feed here.
