### ISSUE TITLE
Commercial support

### ISSUE THREAD

**Issue by SebastienDorgan** [squat/kilo#280]
Hello, Is there a commercial support for Kilo?

**Comment by squat** [comment]
@SebastienDorgan this does not exist today, however it is something that we have been exploring formalizing. Please reach out via slack if you'd like to discuss more.

Otherwise, I know that Scaleway (and perhaps other cloud providers) offers a hosted Multi-Cloud Kubernetes service built in Kilo, for which commercial support is available: https://www.scaleway.com/en/kubernetes-kosmos/

**Comment by squat** [comment]
Closing for now. Will discuss more via other mediums.
