### ISSUE TITLE
does kilo support aws eks with aws-vpc-cni?

### ISSUE THREAD

**Issue by dmitry-mightydevops** [squat/kilo#363]
Hello, 

Does kilo supports aws eks with aws-vpc-cni?

**Comment by squat** [comment]
Hi @dmitry-mightydevops running Kilo on top of other CNIs is experimental and has varying degrees of support. Currently only Flannel and Cilium are known to work. I've never used EKS before and unfortunately this project doesn't have any budget for testing and developing on the relatively expensive hosted Kubernetes offerings.

Furthermore, I'm not sure if this is the case for EKS, but one complicating factor related to hosted Kubernetes offerings is that the hosting of the control plane is often entirely opaque, ie the control plane proceses are run outside of a Kubelet and there are no control plane nodes to speak of. This means that we cannot configure the control plane nodes, since there are no nodes on which to schedule the Kilo daemon set, and the control plane processes cannot form part of the WireGuard mesh, which means that the control plane wouldn't be able to access the Kubelet API endpoints on nodes in networks different from the network running the control plane, essentially reducing the cluster's functionality.

**Comment by dmitry-mightydevops** [comment]
thanks it's clear!
