### ISSUE TITLE
Question: Is the project still maintained?

### ISSUE THREAD

**Issue by namirsab** [squat/kilo#373]
Hi @squat 
First of all thanks for your fantastic work!

In my team, we've been using Kilo for a while through Scaleway. We are wondering if we should stay with them in the next steps, and one of the reasons why we are thinking about this is because we see Kilo might not be maintained anymore. 

Last commit was 10 months ago, and it doesn't seem like issues are been closed or triaged. 

I understand maintaining such a project might take time and effort, but we would like to know what's going to happen or if we shouldn't worry or find different ways of maintaining it.

Thanks in advance!

**Comment by squat** [comment]
Hi yes the project is still maintained! The project is mostly stable and TBH most issues filed are user error, which take much more time to close than bugs because they require lots of teaching.

The main goal I have for the project coming forward is to finish and merge https://github.com/squat/kilo/pull/328

Lateley I've been doing more work behind the scenes trying to get some funding from industry to provide cloud credits for testing. One of the hardest things about maintaining Kilo is the testing various configurations. This requires bringing up lots of cluster configurations. Historically I've done this by reco figuring my personal lab setup and by simulating with Kind, plus some amount of bringing up clusters on paid cloud providers. Reconfiguring my own lab takes a lot of time and it would be extremely helpful going forward to get funding to spend on test infra.

**Comment by squat** [comment]
Closing for now :)
