### ISSUE TITLE
features

### ISSUE THREAD

**Issue by segator** [squat/kilo#4]
- What if nodes have dynamic public IP? is kilo inteligent and auto refresh nodes configuration with the new node public IP?

- Any way to auto detect datacenters? so many nodes in the same DC can directly route without WG?(ip route?)

- This only works on kubernetes I supose.
Check my project, maybe can help you with ideas ;) Good work!!
https://github.com/segator/wireguard-dynamic

**Comment by squat** [comment]
Hi @segator,

Today, the Kilo agent running on each node only checks the public IP once, at launch time. You’re right that it would be a cool, and trivial to implement, feature to watch the public IP for changes and reconcile the WireGuard config as necessary.

Kilo uses the K8s failure-domain.beta.kubernetes.io/region label to try to auto-detect data centers as may be configured by cloud controllers. Otherwise the data centers need to be specified manually using a Kilo annotation. Once the data centers are known, encapsulation within a data center can be turned off so only cross-data center packets are encapsulated. Do you have any ideas around automatic data-center discovery? This would make user’s lives easier so I’d love to add it.

As of right now, Kilo is K8s only, but the backend powering the mesh is abstracted and is just an interface and the K8s logic is contained in just one package, so implementing for other orchestrators would be possible and straightforward.

Thanks for the ideas :) It sounds like you’ve thought about some of these problems and have some ideas about how to solve them. I’d love to hear more and would very happily accept PRs to the project if you’d like to add one of these feautures!

**Comment by segator** [comment]
Hi @squat  I would love to help with PR but right Now I don't have enough time on my daily time :( 
So I would try to help in other ways.


What I did in my implementation:
- **Dynamic Public IP**:  Every X seconds check with some providers node public IP, if diferent publish it to the mesh, so others nodes can discovery the new Public IP and reconfigure the peer endpoint.(I prefer to use stun server to detect public IP)

- **UPnP & UDP HOle punching**: I started some weeks ago the implementation of automatic port configuration, so no required to have a port opened using Router UPnP or UDP Hole punching technique.

- **Nodes Accesibles Without WG**: those nodes that are in the same DC and can directly IP route without WG, to auto detect those nodes I implement a simple web Services, then every node publish the public and private IP, before connect using WG to the public IP i try to conect to the private IP on the webservice, if the response is what I expect(Mean I can reach the node through it's internal ip) then create the IP route. Probably Will be other betters ways to do that, for example sending broadcasting packets? but may not work depending on the network configuration.

**Ip route Example on one of my nodes, that have multiple wg peers and 1 node in the same DC**
```
12.1.1.1 dev wg0 scope link
12.1.1.2 dev wg0 scope link
12.1.1.4 via 192.168.1.200 dev ens192
12.1.1.6 dev wg0 scope link
12.1.1.7 dev wg0 scope link
```

I Also added the option to route networks subnet to a especific node.
For example to go to 10.7.0.0/8 you can go through node 12.1.1.7, this config is published by 12.1.1.7 node on the mesh config, then the rest of the nodes configure this route.


Check my project maybe can help you with new ideas ;) 
Don't blame me because the quality of the code, is my first project in Golang and I don't really know most of the golang develop best practices.

**Comment by squat** [comment]
Thanks for writing back :)

Yes, using a stun server as an optional enhancement for public IP discovery would be helpful as long as it is indeed optional, so it is easy for users to set up their cluster.

Kilo makes nodes without WG routable to the whole mesh including those nodes’ pod subnets. It’s fundamental to making pod networking work.

One possible difference in implementation I see here is that Kilo tries to keep its exposed surface as small as possible, i.e. only require an open UDP port for WG and an accessible K8s API and no extra services. All discovery should be done with just these two requirements to limit exposure as much as possible.

Using broadcast within a data center would be a definitely the correct way to discover local groups of nodes to configure into one region. I’ll definitely prioritize this investigation.

Thanks for your ideas!

If you’re ever on the K8s slack, you can find me there as @squat.

**Comment by segator** [comment]
Happy to help!!
