### ISSUE TITLE
Node public IP?

### ISSUE THREAD

**Issue by stobias123** [squat/kilo#6]
Hi - came across your project, I was curious if it would be possible to run the nodes in client mode without an exposed port? I know this is possible in wireguard, and it surprises me I can't seem to do it with this or wormhole.

**Comment by squat** [comment]
Hmm so if I understand you correctly you don’t want to connect nodes in th cluster using Kilo and instead want to run Kilo as a gateway from your cluster to connect to a WireGuard server that does have a public IP? Is that right?

You can do this today with Kilo. If Kilo cannot determine your node’s public IP it will select the best IP (likely a private IP) it can find and advertise this to the other nodes in the cluster. However, if Kilo is just a gateway to an external WireGuard server, then all intra-cluster traffic will not be over WireGuard and the lack of public IP will not matter. You can still create a Peer custom resource to tell Kilo about the WireGuard server and the correct routes to the allowed IPs will be created.

Public IPs and exposed ports will always be needed if you want to connect multiple nodes in the cluster to each other because those nodes are clients and servers for one another. But if you don’t need that feature and just want to consume a service over WireGuard then you can do without it.

Please let me know if you had something else in mind.

**Comment by merqurio** [comment]
We would like to deploy a cluster similarly too, and we have some doubts. Maybe we can discuss it in a `kilo` IRC channel ? I would love to hear about @stobias123 case too

**Comment by squat** [comment]
sounds good, you can find me on freenode as `squat` :) let's try to keep the issue here informed after the discussion so that future users can find answers as well. I can also update/add docs as necessary

**Comment by squat** [comment]
Closing this since there was no response. Please feel free to comment again to follow up :)
