### ISSUE TITLE
Force *in*ternal IP?

### ISSUE THREAD

**Issue by OJFord** [squat/kilo#7]
Is it possible to specify the internal IP that a node should use?

Or, if not that granular (or not possible/desirable for some reason?) - a CIDR block for the location?

Project looks great by the way - I'm currently running Wireguard on the hosts and using kube-router for CNI, so tempted to collapse that into just kilo.

**Comment by squat** [comment]
@OJFord, it is not possible today but not for any reason other than I hadn’t thought of it as a necessary use case. Thinking about it again I can certainly imagine that the heuristics Kilo uses to select an internal IP may not always serve every use case and an equivalent “force-internal-ip” annotation can certainly make sense. Adding that feature would be quite simple. If you’re temped to make a PR, I would happily review it, otherwise I can make it and ping this thread when it’s up.

**Comment by OJFord** [comment]
I'll have a go perhaps this weekend, thanks!

**Comment by squat** [comment]
@OJFord I went ahead and made the changes today to allow overriding the internal IP. There now exists a `force-internal-ip` annotation for that purpose: https://github.com/squat/kilo/blob/master/docs/annotations.md#force-internal-ip.

Plz re-open if you have any issues :)
