### ISSUE TITLE
How to setup custom private keys?

### ISSUE THREAD

**Issue by plicon** [squat/kilo#79]
When setting up kilo private keys for the server are generated automagically. Is it possible to create/define your own private keys? That would really help for automated deployments.

**Comment by squat** [comment]
Hi @plicon :)) configuring Kilo to use an existing private key is totally possible. I think this could be a really helpful guide.

Kilo will load any private key located in `/var/lib/kilo/key`. If no private key is found, then a new one will be generated. Once a private key is available, the key will be reused until it is deleted. If a key is deleted and the Kilo process is restarted, then a new key will be generated.

Note, every node must have a unique private key.

Today, the path from which private keys are loaded is hardcoded, which makes it difficult to configure the private keys for an entire cluster using a secret. This is because the secret must have a different entry for each node so the resulting mount path for each node would be different. However, adding the functionality to load a private key from any path would be quite easy.

**Comment by plicon** [comment]
thanks for your reply .. I'll give it a go. Already found the key in /var/lib/kilo but simply overwriting and restarting the DaemonSet didn't do the trick. Good to know it has to be there before kilo is started. 
Thanks so far!

**Comment by squat** [comment]
Hi @plicon, any update on your effort to set the keys?

**Comment by squat** [comment]
Assuming this is working :) please reopen of you still have any issues!
