### ISSUE TITLE
kgctl showconf peer on multi-clusters

### ISSUE THREAD

**Issue by AntonOfTheWoods** [squat/kilo#85]
I have two full-mesh clusters I am connecting, and I am trying to set up my laptop to connect to them. When I run:

```
kgctl --kubeconfig ~/cluster1.conf showconf peer mylaptop
```
As instructed [here](https://kilo.squat.ai/docs/vpn) against either of the two clusters, I *also* get the config for the other cluster, but strangely the config only seems to be complete for the *other* cluster. By that I mean that I also get the service CIDR on one of the peer configurations for that cluster. I *don't* get the service CIDR for the cluster I am executing `showconf peer` against. Now obviously I can just add the service CIDR manually to whichever cluster is missing it but I'd quite like to know whether this is expected, and whether it is Ok.

**Comment by squat** [comment]
Hi @AntonOfTheWoods, yes this is exactly as expected. This is because within a single cluster, Kilo knows nothing about service CIDRs. Service CIDRs should always be routable within a cluster, and when a service IP NATs to a Pod IP only routable by Kilo, e.g. the node is in another cloud, then Kilo takes over. For this reason, a Kilo config inside of a cluster is completely agnostic to service CIDRs.

That said, if you want your VPN client to route all requests to service CIDRs over WireGuard, then manually adding the service CIDR to one of the `[Peer]` sections of the generated config is the right way to go. I think it would be a great addition to document this as a `_Note_` in the VPN doc (contributions are very welcome :D). Eventually it could be nice to add an option to the `showconf` command that accepts a mapping of public keys to additional CIDRs, however this is a tricky user experience since the user probably doesn't know what the public key of the node is off the top of their head. If you have any ideas for a new feature, please open a feature proposal issue so we can figure out a good design :)

Thanks!

**Comment by AntonOfTheWoods** [comment]
Thanks for your reply @squat . I am still coming to terms with Kube networking so I guess it is all logical once you know what you're doing. One thing I did note - there is a `--allowed-ips` option, which you have in the example for the `SERVICECIDR`s, and is only taken into account with the `--as-peer` option. It seems like an almost identical use, so could that just be used for this purpose? 
I will definitely be keen to contribute, at least some extra docs. I'll try and get some more handy tips and then submit something for your consideration.

**Comment by squat** [comment]
You're right about that option, however `--allowed-ips` only makes sense when doing `kgctl get [node|peer] --as-peer` because it is unambiguous where to put these additional allowed IPs. On the other hand, when doing `showconf`, the returned configuration will contain configs for potentially multiple WireGuard peers, so it's not clear where to put the IPs.

We could reuse the flag name for the show and command but its functionality and syntax would need to be adapted.

**Comment by AntonOfTheWoods** [comment]
I was wondering how it was calculated because it definitely "works" for the "other" cluster, ie, if I ask for the showconf for cluster A then it will add the service CIDR to one (and only one) of the peers from cluster B. It happened to be the first cluster node. I had thought it would choose a node that I manually marked as being a leader but it reliably chose the first node I created in that cluster (also the first alphabetically). Could it use the same algorithm for choosing the leader to decide who to put the service CIDR on?
