### ISSUE TITLE
not getting proper topology

### ISSUE THREAD

**Issue by pratikbalar** [squat/kilo#88]
Hello,
i have two k3s cluster cluster1 -> pratik(single node) and  cluster2 ->  3 node HA-all-masters (nodes hacluster-node-1/2/3), successfully annotate cluster2's nodes to location2, and cluster1 to location1.
I'm trying to create [multi-cluster-services](https://github.com/squat/kilo/blob/master/docs/multi-cluster-services.md) and i followed that doc precise.

---

but first time got below topology in which that cluster1 have no kilo ip as cluster2 have i.e. 10.4.0.1
![image](https://user-images.githubusercontent.com/68642400/98808844-ce267380-2442-11eb-84dc-0796e5eb9c09.png)

---

then after creating everything from start, second time got this in which cluster1 have kilo ip i.e. 10.4.0.1 but cluster2's nodes are also not connected, even i checked it with `wg show` other two nodes are not wg configured 
![image](https://user-images.githubusercontent.com/68642400/98808850-cf57a080-2442-11eb-92b1-77d70cafe0ac.png)

---

`wg configs` of all nodes
* cluster1's 
![image](https://user-images.githubusercontent.com/68642400/98813103-af77ab00-2449-11eb-9e39-0b2bde542bd2.png)

* cluster2's hacluster-node-1 
![image](https://user-images.githubusercontent.com/68642400/98813249-e6e65780-2449-11eb-9084-689c4080fa02.png)

* cluster2's hacluster-node-2/3
![image](https://user-images.githubusercontent.com/68642400/98813327-febddb80-2449-11eb-9dc0-d78b3258d301.png)

**Comment by squat** [comment]
Hi @pratikbalar both of the topologies you showed here seem mostly correct and topologically equivalent; they differ only in the perspective from which `kgctl graph` was run.

Each cluster has 1 location and correspondingly 1 active WireGuard endpoint. That is, `cluster 1` has `pratik` and `cluster 2` has `hacluster-node-1`. When you peer two clusters, what you are really doing is registering every _active_ WireGuard endpoint in one cluster as a WireGuard peer of the other cluster. This is why, when you run `kgctl graph` from the perspective of `cluster 1`, you only see two endpoints: `pratik` and `hacluster-node-1`, because `hacluster-node-1` is was the only active node. In other words, from the point of view of `cluster 1`, there are only 2 endpoints in the entire mesh, `pratik` and `hacluster-node-1`, the latter of which serves as the gateway for several allowed-ips, which it turns out represent other nodes, but `cluster 1` doesn't know anything about that.

Note: when you add a Peer resource to a Kilo mesh, Kilo will not know anything about "kilo IPs" for that peer; instead it will only know about that peer's allowed IPs. This list of allowed IPs may include an IP which _is_ a Kilo IP inside of the peer, but it makes no difference from the point of view of the mesh. This is because the Kilo mesh cannot allocate the IPs for the peer and thus it does not make sense for the mesh know if the IPs are "Kilo IPs" or not. This is the reason why we set the constraint that peered clusters _must_ have non-overlapping CIDRs, since there is no global IP allocator that can take care of this.

Furthermore, the `kgctl graph` command does not show the allowed IPs for peers. This is why the first graph doesn't show any IPs other than the endpoint for `pratik` and why the second graph doesn't show any IPs other than the endpoint for `hacluster-node-1`. This is simply the design today. Perhaps this is why you think there is a problem?

One problem I see is that it seems that both of your clusters have exactly the same Kilo CIDR: 10.4.0.0/24. This means that the active WireGuard endpoint in each cluster, i.e. `pratik` and `hacluster-node-1` are each getting assigned the IP 10.4.0.1/24. As a result, the clusters will not be able to communicate properly.

Another odd detail, although it is not necessarily incorrect, is that locations only need to be unique _within_ clusters, not between them. When you peer two clusters together, their nodes will _always_ be treated as separate locations because one cluster does not know anything about the locations of the other. For this reason, you do not need to annotate one cluster's nodes as `location 1` and the other's as `location 2`. Instead, you could use the default, i.e. un-annotated, location for each cluster.

Looking forward to your reply :)

**Comment by pratikbalar** [comment]
hello @squat Thanks for Fast-as-Flash reply,
I understand your `location`explanation, i just wanted to be safe with that's why i annotate all 3 nodes with `location2` in `cluster2` and single node with `location1` in `cluster1`

so i can ping `10.4.0.1`(which is `hacluster-node-1`) from cluster1 `pratik`node, but i can't access any services from `cluster2` in `cluster1` after creating endpoints.

**Comment by squat** [comment]
> i can't access any services from cluster2 in cluster1 after creating endpoints. do i have to configure iptables or something else?
No, iptables rules should be necessary. All of that is taken care of by Kilo as long as `pratik` is a Kubernetes node and not simply a laptop that is not running Kilo. Could you share your configuration for `pratik`? This would help us debug: `kgctl showconf peer pratik --as-peer --allowed-ips=$ANY_IPS_YOU_ADDED`

> pratik node have no ip like 10.4.0.x as hacluster-node-1 have (10.4.0.1)
This is what I was trying to explain in my answer above. I apologize if it was not clear. As you can see in your second graph, the `pratik` node DOES have a Kilo IP: it is 10.4.0.1. This is a problem: your two clusters _must_ have non-overlapping Kilo CIDRs. Can you share the output of `kubectl get node pratik -o jsonpath='{.metadata}'` so that we can see the annotations on the `pratik` node?

**Comment by pratikbalar** [comment]
Thanks for fast reply @squat, and sorry the confusions. 
> Could you share your configuration for pratik?
all the nodes are digitalocean droplets and `pratik` is without private networking where and `cluster2`'s all nodes are private network enabled.

![image](https://user-images.githubusercontent.com/68642400/98917660-aabb0180-24f2-11eb-93fe-36fa4087713d.png)
![image](https://user-images.githubusercontent.com/68642400/98917839-e229ae00-24f2-11eb-9718-5bef0ae90ffb.png)

> `kubectl get node pratik -o jsonpath='{.metadata}' `

![image](https://user-images.githubusercontent.com/68642400/98918642-e0acb580-24f3-11eb-865a-e24254fe1b9f.png)

**Comment by squat** [comment]
Hi @pratikbalar, yes the problem is that both of your clusters have overlapping Kilo CIDRs. You can see this because both `pratik` and `hacluster-node-1` have 10.4.0.1 in their allowed IPs. To fix this, you need to change the Kilo DaemonSet configuration on one of the cluster. Specifically, you need to change the Kilo subnet by appending the `--subnet` flag to the arguments list of the Kilo container (https://github.com/squat/kilo/blob/master/manifests/kilo-k3s.yaml#L105), e.g. add `--subnet=10.5.0.0/24`

**Comment by pratikbalar** [comment]
@squat It's working, so i tried to connect my-laptop with droplet using kilo and it's working after changing kilo's `subnet` from daemonset as you said. Thanks for amazing **support** and **product** man.

---

> yes the problem is that both of your clusters have overlapping Kilo CIDRs. You can see this because both `pratik` and `hacluster-node-1` have 10.4.0.1 in their allowed IPs. To fix this, you need to change the Kilo DaemonSet configuration on one of the cluster. Specifically, you need to change the Kilo subnet by appending the `--subnet` flag to the arguments list of the Kilo container (https://github.com/squat/kilo/blob/master/manifests/kilo-k3s.yaml#L105), e.g. add `--subnet=10.5.0.0/24`

**Comment by pratikbalar** [comment]
@squat It's working, so i tried to connect my-laptop with droplet using kilo and it's working after changing kilo's `subnet` from daemonset as you said. Thanks for amazing **support** and **product** man.

---

> yes the problem is that both of your clusters have overlapping Kilo CIDRs. You can see this because both `pratik` and `hacluster-node-1` have 10.4.0.1 in their allowed IPs. To fix this, you need to change the Kilo DaemonSet configuration on one of the cluster. Specifically, you need to change the Kilo subnet by appending the `--subnet` flag to the arguments list of the Kilo container (https://github.com/squat/kilo/blob/master/manifests/kilo-k3s.yaml#L105), e.g. add `--subnet=10.5.0.0/24`
